### PR TITLE
Change `version` to a Development Tag

### PR DESCRIPTION
**Pull request by Deleh**
ref https://github.com/4am-robotics/orga/issues/4739

This prevents the *New release available!* popup and since we're using already a "custom" version it fits better than the default `version` tag.

### CODE REVIEW

**Comment by Deleh** [comment]
@fmessmer An alternative to this would be to replace the hardcoded URL with the release tags of our repos:

https://github.com/mojin-robotics/flexbe_app/blob/56cf0b231d26f5212a4fdb008e1e7a17fcb07841/src/ui/ui_feed.js#L6

We would then need to update the `package.json` for every new tag.

**Comment by benmaidel** [comment]
When we sync our fork with the latest release from flexbe also the package.json should be synced and thus the version tag should match to the latests available release. So there should not be any more warnings about a newer version. If flexbe released a new version it is valid to have a warning on the GUI even if we are using our own fork. So we always know if it would make sense to check if a new sync should be done.

**Review by benmaidel — CHANGES_REQUESTED** [review]
When we sync our fork with the latest release from flexbe also the package.json should be synced and thus the version tag should match to the latests available release. So there should not be any more warnings about a newer version. If flexbe released a new version it is valid to have a warning on the GUI even if we are using our own fork. So we always know if it would make sense to check if a new sync should be done.

In my option we should merge the package.json instead of adding a version tag that is not existing.

**Comment by Deleh** [comment]
> When we sync our fork with the latest release from flexbe also the package.json should be synced and thus the version tag should match to the latests available release. So there should not be any more warnings about a newer version. If flexbe released a new version it is valid to have a warning on the GUI even if we are using our own fork. So we always know if it would make sense to check if a new sync should be done.
> 
> In my option we should merge the package.json instead of adding a version tag that is not existing.

This would be the optimal solution but I don't think this is easily possible. We are using the ROS 1 version of FlexBE where the last [`package.json`](https://github.com/FlexBE/flexbe_app/blob/noetic/package.json) update was commited 3 years ago to version `2.3.0`. Current development seems to happen on the [`ros2-devel`](https://github.com/FlexBE/flexbe_app/blob/ros2-devel/package.json) branch. The latest releases are also based on the ROS 2 branch, so our ROS 1 FlexBE app is comparing it's release version against the ROS 2 release.. (could you please verify this?)

If I saw this correctly we could either:
1. Keep the warning and ignore it
2. Cherry-pick the `ros2-devel` commit for `package.json`
3. Update to a non-existing tag as currently in the PR
4. Adjust the hard-coded URL

I'd go with 1, 3 or 4.

**Comment by HannesBachter** [comment]
I get the following error when changing the `package.json`:
```
[ERROR] [1695224602.781148]: /behavior_launcher(_SubscriberImpl._invoke_callback): bad callback: <bound method BehaviorLauncher._version_callback of <flexbe_widget.behavior_launcher.BehaviorLauncher object at 0x7f842a6a8a60>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/u/kessel/git/mojin_ws/src/flexbe_behavior_engine/flexbe_widget/src/flexbe_widget/behavior_launcher.py", line 122, in _version_callback
    vui = self._parse_version(msg.data)
  File "/u/kessel/git/mojin_ws/src/flexbe_behavior_engine/flexbe_widget/src/flexbe_widget/behavior_launcher.py", line 133, in _parse_version
    result += int(n) * offset
ValueError: invalid literal for int() with base 10: '4am-dev'

**Comment by Deleh** [comment]
> I get the following error when changing the `package.json`:
> 
> ```
> [ERROR] [1695224602.781148]: /behavior_launcher(_SubscriberImpl._invoke_callback): bad callback: <bound method BehaviorLauncher._version_callback of <flexbe_widget.behavior_launcher.BehaviorLauncher object at 0x7f842a6a8a60>>
> Traceback (most recent call last):
>   File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
>     cb(msg)
>   File "/u/kessel/git/mojin_ws/src/flexbe_behavior_engine/flexbe_widget/src/flexbe_widget/behavior_launcher.py", line 122, in _version_callback
>     vui = self._parse_version(msg.data)
>   File "/u/kessel/git/mojin_ws/src/flexbe_behavior_engine/flexbe_widget/src/flexbe_widget/behavior_launcher.py", line 133, in _parse_version
>     result += int(n) * offset
> ValueError: invalid literal for int() with base 10: '4am-dev'
> ```

Ah correct, I've just tested it with the `--offline` flag, not `flexbe_full.launch`.. I'll adjust the URL for now, this is probably the cleanest solution.

**Review by fmessmer — APPROVED** [review]
- I guess comparing to `mojin-robotics/flexbe_app` makes sense
- I synced the versions of `package.xml` and `package.json`
- I will push a tag for `2.4.0` to our fork

**Comment by fmessmer** [comment]
I used `catkin_prepare_release` to create a new tag....it had to be `2.4.2`...and I also had to remove the tags `3.*.*` because it was still comparing against those higher version tags...

**Pull request merged**
